#!/usr/bin/env python3
"""Build the lean MDSE runtime base from the W-321 release manifest.

Usage:
  python3 99_System/09_Tools/build-base.py OUTPUT_DIRECTORY

The output directory must not already contain files. The positive include list comes only
from 99_System/03_Schemas/mdse-release.yaml. Workspace-only methodology files are never
copied. During pre-release, a not-yet-built conditional file (currently importer v0.8.0)
is reported and skipped; release status 'release' makes it blocking.
"""
import argparse, os, shutil, sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),"..",".."))
MANIFEST=os.path.join(ROOT,"99_System","03_Schemas","mdse-release.yaml")

def full(root,p):
    return os.path.join(root,*p.split("/"))

def copy_file(src_root,dst_root,p):
    src=full(src_root,p); dst=full(dst_root,p)
    if not os.path.isfile(src):
        raise FileNotFoundError(p)
    os.makedirs(os.path.dirname(dst),exist_ok=True)
    shutil.copy2(src,dst)

def copy_tree(src_root,dst_root,p):
    src=full(src_root,p); dst=full(dst_root,p)
    if not os.path.isdir(src):
        raise FileNotFoundError(p)
    for d,dirs,names in os.walk(src):
        dirs[:]=[x for x in dirs if x!=".git"]
        rel=os.path.relpath(d,src)
        out=dst if rel=="." else os.path.join(dst,rel)
        os.makedirs(out,exist_ok=True)
        for n in names:
            shutil.copy2(os.path.join(d,n),os.path.join(out,n))

ap=argparse.ArgumentParser()
ap.add_argument("output")
a=ap.parse_args()
out=os.path.abspath(a.output)

with open(MANIFEST,encoding="utf-8") as f:
    man=yaml.safe_load(f)
rb=man["runtimeBase"]

if os.path.exists(out):
    if not os.path.isdir(out):
        sys.exit(f"Output exists and is not a directory: {out}")
    if os.listdir(out):
        sys.exit(f"Output directory is not empty; refusing to overwrite: {out}")
else:
    os.makedirs(out)

copied=0
for p in rb["includeFiles"]:
    copy_file(ROOT,out,p); copied+=1
for p in rb["includeTrees"]:
    before=sum(len(ns) for _,_,ns in os.walk(full(ROOT,p)))
    copy_tree(ROOT,out,p); copied+=before

for p in rb.get("conditionalFiles",[]):
    if os.path.isfile(full(ROOT,p)):
        copy_file(ROOT,out,p); copied+=1
    elif man["releaseStatus"]=="release":
        sys.exit(f"Release runtime file is missing: {p}")
    else:
        print(f"WARN pre-release runtime file not built yet: {p}")

vault=f'''# Generated by build-base.py from mdse-release.yaml. Do not remove mdse_release.
vault_uid: UNINITIALIZED
name: MDSE_Base_Vault
default_branch: main
mdse_release: "{man["mdseRelease"]}"
'''
with open(full(out,".vault.yaml"),"w",encoding="utf-8",newline="\n") as f:
    f.write(vault)

readme=f'''# MDSE Base Vault

Lean runtime base for MDSE release **{man["mdseRelease"]}**.

Runtime schemas:
- relationships {man["schemas"]["relationships"]}
- element-types {man["schemas"]["elementTypes"]}
- Local Model {man["schemas"]["localModel"]}

This vault intentionally does not contain the methodology workspace's Current State,
release manifest, Translator Definition, Decision Log, EA evidence, archives, or
Workbench design notes. Runtime rules are in
`99_System/10_Docs/MDSE Modeling Ruleset 1.23.md` and the schemas under
`99_System/03_Schemas`.

Before use, initialize `.vault.yaml` once with `Initialize-Vault.sh` or
`Initialize-Vault.ps1`. Initialization changes the vault UID/name and preserves
`mdse_release`.
'''
with open(full(out,"README.md"),"w",encoding="utf-8",newline="\n") as f:
    f.write(readme)

for p in rb.get("forbiddenPaths",[]):
    if os.path.exists(full(out,p)):
        sys.exit(f"Forbidden workspace-only path leaked into runtime base: {p}")

lock_path=full(out,".obsidian/plugin-lock.yaml")
lock=open(lock_path,encoding="utf-8").read() if os.path.exists(lock_path) else ""
if man["tools"]["bootstrap"]["sourceAvailable"] is False and "mdse-bootstrap" in lock:
    sys.exit("Unavailable mdse-bootstrap is present in the generated runtime plugin lock")
wbid=man["tools"]["workbench"]["runtimePluginId"]
if man["releaseStatus"]=="release" and man["tools"]["workbench"]["requiredForRelease"] and wbid not in lock:
    sys.exit("Release base does not pin the required WB-106-capable Workbench")

print(f"Built MDSE {man['mdseRelease']} lean runtime base at {out}")
print(f"Copied {copied} governed source files plus generated README.md and .vault.yaml")
print("Validate with: python3 99_System/09_Tools/check-release.py --base <output>")
