#!/usr/bin/env python3
"""Generate the governed plugin configuration of the MDSE runtime base (W-322).

Usage:
  python3 "Base Vault/Tools/v0.8.0-r2/build-plugin-config.py"          # write generated files
  python3 "Base Vault/Tools/v0.8.0-r2/build-plugin-config.py" --check  # exit 1 if any generated file is stale

Inputs (authority): 99_System/03_Schemas/relationships.yaml, element-types.yaml.
Outputs (generated, never edit by hand):
  99_System/06_Fileclasses/<Class>.md               Fileclass schema per MDSE class (bound by `type`)
  99_System/06_Fileclasses/MDSE Link Targets.base   candidate lists for relationship fields
  Base Vault/Runtime/Plugins/<id>/data.json governed settings for breadcrumbs, fileclass,
                                                    templater-obsidian, obsidian-git
Plugin code (main.js, manifest.json, styles.css) in Base Vault/Runtime/Plugins is vendored, not generated. The generated banner is intentionally byte-stable for the current v0.8 pre-release and will be refreshed only in a deliberate regeneration step.
"""
import argparse, hashlib, json, os, sys
try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SCHEMAS = os.path.join(ROOT, "99_System", "03_Schemas")
FC_DIR = "99_System/06_Fileclasses"
TARGETS = FC_DIR + "/MDSE Link Targets.base"
PAYLOAD = "Base Vault/Runtime/Plugins"
EXCLUDED_FOLDERS = ["99_System", "Definitions", "Workbench Views"]
STATUS_VALUES = ["Draft", "Active", "Retired"]          # values in use (Definitions/Properties/status.md)
NOT_AUTHORED = {"equals"}                               # historical temporary field; absent from current 1.36 authority
ANY_VIEW = "Any model note"
HEADER = "GENERATED by 99_System/09_Tools/build-plugin-config.py from relationships.yaml and element-types.yaml (W-322). Do not edit; change the schemas and regenerate."

def load(n):
    with open(os.path.join(SCHEMAS, n), encoding="utf-8") as f:
        return yaml.safe_load(f)

rel, et = load("relationships.yaml"), load("element-types.yaml")
classes = [c["name"] for c in et["classes"]]
subtypes = {c["name"]: list(c.get("subtype") or []) for c in et["classes"]}

def ends(v):
    return "any" if v in (None, "any") else list(v)

# Ordered relationship definitions (W-97: relationship fields in the order of relationships.yaml).
defs = []   # (field, inverse or None, from, to, kind, sameClass)
excl = {}   # field -> {fromClass: {excluded target classes}}
for p in rel["paired"]:
    defs.append((p["forward"], p["inverse"], ends(p.get("from")), ends(p.get("to")), "paired", bool(p.get("sameClass"))))
    for a_, b_ in p.get("excludePairs") or []:
        excl.setdefault(p["forward"], {}).setdefault(a_, set()).add(b_)
for p in rel.get("temporaryPairs", []):
    defs.append((p["forward"], p["inverse"], ends(p.get("from")), ends(p.get("to")), "temporary", False))
for p in rel["symmetric"]:
    b = ends(p.get("between"))
    defs.append((p["field"], None, b, b, "symmetric", False))
for p in rel["oneWay"]:
    if isinstance(p, str):
        defs.append((p, None, "any", "any", "oneWay", False))
    else:
        defs.append((p["field"], None, ends(p.get("from")), ends(p.get("to")), "oneWay", False))

def view_name(targets):
    return ANY_VIEW if targets == "any" else " | ".join(sorted(targets))

def fid(*parts):
    h = hashlib.sha1("/".join(parts).encode()).hexdigest()
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    n = int(h, 16)
    return "".join(alphabet[(n >> (6 * i)) % 62] for i in range(6))

def yq(s):
    return json.dumps(s, ensure_ascii=False)

out = {}
views = {}

# ---- Fileclass class notes
for c in classes:
    fields = [("id", "Input", None), ("uid", "Input", None)]
    if subtypes[c]:
        fields.append(("subtype", "Select", {"sourceType": "ValuesList", "valuesList": {str(i + 1): v for i, v in enumerate(subtypes[c])}}))
    fields.append(("status", "Select", {"sourceType": "ValuesList", "valuesList": {str(i + 1): v for i, v in enumerate(STATUS_VALUES)}}))
    for field, inv, frm, to, kind, same in defs:
        if field in NOT_AUTHORED:
            continue
        if frm != "any" and c not in frm:
            continue
        targets = [c] if same else to
        ex = excl.get(field, {}).get(c, set())
        if ex:
            targets = [x for x in (classes if targets == "any" else targets) if x not in ex]
        vn = view_name(targets)
        views[vn] = targets
        fields.append((field, "MultiFile", {"baseFile": TARGETS, "viewName": vn}))
    lines = ["---", "# " + HEADER, "version: \"2.0\"", "limit: 20", "mapWithTag: false", "icon: file-spreadsheet", "fields:"]
    for name, typ, opts in fields:
        lines += [f"  - name: {name}", f"    id: {fid(c, name)}", f"    type: {typ}", "    path: \"\""]
        if opts is None:
            lines.append("    options: {}")
        else:
            lines.append("    options:")
            for k, v in opts.items():
                if isinstance(v, dict):
                    lines.append(f"      {k}:")
                    for kk, vv in v.items():
                        lines.append(f"        {yq(kk)}: {yq(vv)}")
                else:
                    lines.append(f"      {k}: {yq(v)}")
    lines += ["---", f"# {c}", "", f"Fileclass schema for notes with `type: {c}`. Generated; see `99_System/01_Admin/Enabled Plugin Stack.md`.", ""]
    out[f"{FC_DIR}/{c}.md"] = "\n".join(lines)

# ---- Link-target base
views.setdefault(ANY_VIEW, "any")
bl = ["# " + HEADER, "filters:", "  and:"]
bl += [f"    - '!file.inFolder({yq(f)})'" for f in EXCLUDED_FOLDERS]
bl += ["    - 'file.ext == \"md\"'", "    - '!note.type.isEmpty()'", "views:"]
for vn in sorted(views, key=lambda v: (v != ANY_VIEW, v)):
    t = views[vn]
    bl += ["  - type: table", f"    name: {yq(vn)}"]
    if t != "any":
        bl += ["    filters:", "      or:"] + [f"        - 'note.type == {yq(x)}'" for x in t]
    bl += ["    order:", "      - file.name", "      - type", "      - id", "    sort:", "      - property: file.name", "        direction: ASC"]
out[TARGETS] = "\n".join(bl) + "\n"

# ---- Breadcrumbs (4.x): every relationship field is an edge field; persisted inverses are also implied.
UP = ["partOf", "childOf", "stateOf", "includedIn"]
DOWN = ["hasPart", "hasChild", "hasState", "includes"]
GEN = ["subtypeOf", "supertypeOf"]
SAME = [d[0] for d in defs if d[4] == "symmetric"]
NEXT, PREV = ["precedes"], ["follows"]
all_fields, outgoing, incoming = [], [], []
for field, inv, *_ in defs:
    all_fields.append(field)
    if inv:
        all_fields.append(inv)
grouped = set(UP + DOWN + GEN + SAME + NEXT + PREV)
for field, inv, frm, to, kind, same in defs:
    if field not in grouped:
        outgoing.append(field)
    if inv and inv not in grouped:
        incoming.append(inv)
groups = [("ups", UP), ("downs", DOWN), ("sames", SAME), ("nexts", NEXT), ("prevs", PREV),
          ("generalization", GEN), ("outgoing", outgoing), ("incoming", incoming)]
transitive = []
for field, inv, frm, to, kind, same in defs:
    if inv:
        transitive.append({"name": "", "rounds": 1, "chain": [{"field": field}], "close_field": inv, "close_reversed": True})
        transitive.append({"name": "", "rounds": 1, "chain": [{"field": inv}], "close_field": field, "close_reversed": True})
    elif kind == "symmetric":
        transitive.append({"name": "", "rounds": 1, "chain": [{"field": field}], "close_field": field, "close_reversed": True})
bc = {
    "_generated": HEADER,
    "edge_fields": [{"label": f} for f in all_fields],
    "edge_field_groups": [{"label": g, "fields": fs} for g, fs in groups],
    "implied_relations": {"transitive": transitive},
    "self_is_sibling": [],
    "exclude_folders": EXCLUDED_FOLDERS,
    "views": {
        "page": {"trail": {"enabled": True, "field_group_labels": ["ups"]},
                 "prev_next": {"enabled": True, "field_group_labels": {"prev": ["prevs"], "next": ["nexts"]}}},
        "side": {"matrix": {"field_group_labels": [g for g, _ in groups]},
                 "tree": {"field_group_labels": ["downs"], "find_root_field_group_labels": ["ups"]}},
    },
}
out[f"{PAYLOAD}/breadcrumbs/data.json"] = json.dumps(bc, indent=2) + "\n"

out[f"{PAYLOAD}/fileclass/data.json"] = json.dumps({
    "classFilesPath": FC_DIR + "/", "fileClassAlias": "type", "globalFileClass": "", "basesFolder": "",
    "insertFieldsOnBind": False, "openFieldsOnCreate": False, "reorderOnInsert": False,
    "unknownKeysPosition": "bottom", "enableSchemaLog": False, "enableCanvasEngine": False,
}, indent=2) + "\n"

out[f"{PAYLOAD}/templater-obsidian/data.json"] = json.dumps({
    "data_version": 2, "command_timeout": 15, "templates_folder": "99_System/05_Templates",
    "templates_pairs": [], "trigger_on_file_creation_mode": "none", "auto_jump_to_cursor": False,
    "user_scripts_folder": "", "folder_templates": [], "file_templates": [], "syntax_highlighting": True,
    "enabled_templates_hotkeys": [], "startup_templates": [], "ignore_folders_on_creation": [],
}, indent=2) + "\n"

out[f"{PAYLOAD}/obsidian-git/data.json"] = json.dumps({
    "commitMessage": "{{hostname}}: {{numFiles}} files, {{date}}",
    "autoCommitMessage": "{{hostname}}: {{numFiles}} files, {{date}}",
    "autoSaveInterval": 0, "autoPushInterval": 0, "autoPullInterval": 0, "autoPullOnBoot": True,
    "pullBeforePush": True, "syncMethod": "merge", "disablePush": False,
    "disablePopupsForNoChanges": True, "listChangedFilesInMessageBody": True,
    "showStatusBar": True, "showBranchStatusBar": True, "changedFilesInStatusBar": True,
}, indent=2) + "\n"

ap = argparse.ArgumentParser(); ap.add_argument("--check", action="store_true"); a = ap.parse_args()
stale = []
expected_fc = {p for p in out if p.startswith(FC_DIR + "/")}
fc_abs = os.path.join(ROOT, *FC_DIR.split("/"))
if os.path.isdir(fc_abs):
    for n in os.listdir(fc_abs):
        p = FC_DIR + "/" + n
        if p not in expected_fc:
            stale.append(p + " (not generated; remove it)")
for p, text in out.items():
    fp = os.path.join(ROOT, *p.split("/"))
    cur = open(fp, encoding="utf-8").read() if os.path.exists(fp) else None
    if cur != text:
        stale.append(p)
        if not a.check:
            os.makedirs(os.path.dirname(fp), exist_ok=True)
            with open(fp, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
if a.check:
    for s in stale: print("STALE", s)
    print(f"{len(out)} generated files, {len(stale)} stale")
    sys.exit(1 if stale else 0)
print(f"{len(out)} generated files; {len(stale)} written or updated")
