#!/usr/bin/env python3
"""Build the lean MDSE runtime base from the W-321 release manifest.

Usage:
  python3 "Base Vault/Tools/v0.8.0/build-base.py" OUTPUT_DIRECTORY

The output directory must not already contain files. The positive include list comes only
from 99_System/03_Schemas/mdse-release.yaml. Workspace-only methodology files are never
copied. During pre-release, a not-yet-built conditional file (currently importer v0.8.0)
is reported and skipped; release status 'release' makes it blocking.
"""
import argparse, os, shutil, sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),"..","..",".."))
MANIFEST=os.path.join(ROOT,"Base Vault","Definition","mdse-release.yaml")

def full(root,p):
    return os.path.join(root,*p.split("/"))

def copy_file(src_root,dst_root,p):
    copy_file_as(src_root,dst_root,p,p)

def copy_file_as(src_root,dst_root,source,target):
    src=full(src_root,source); dst=full(dst_root,target)
    if not os.path.isfile(src):
        raise FileNotFoundError(source)
    os.makedirs(os.path.dirname(dst),exist_ok=True)
    shutil.copy2(src,dst)

def copy_tree(src_root,dst_root,p):
    src=full(src_root,p); dst=full(dst_root,p)
    if not os.path.isdir(src):
        raise FileNotFoundError(p)
    for d,dirs,names in os.walk(src):
        dirs[:]=[x for x in dirs if x!=".git"]
        rel=os.path.relpath(d,src)
        out=dst if rel=="." else os.path.join(dst,rel)
        os.makedirs(out,exist_ok=True)
        for n in names:
            shutil.copy2(os.path.join(d,n),os.path.join(out,n))

ap=argparse.ArgumentParser()
ap.add_argument("output")
a=ap.parse_args()
out=os.path.abspath(a.output)

with open(MANIFEST,encoding="utf-8") as f:
    man=yaml.safe_load(f)
rb=man["runtimeBase"]

if os.path.exists(out):
    if not os.path.isdir(out):
        sys.exit(f"Output exists and is not a directory: {out}")
    if os.listdir(out):
        sys.exit(f"Output directory is not empty; refusing to overwrite: {out}")
else:
    os.makedirs(out)

copied=0
for p in rb["includeFiles"]:
    copy_file(ROOT,out,p); copied+=1
for m in rb.get("mappedFiles",[]):
    copy_file_as(ROOT,out,m["source"],m["target"]); copied+=1
for p in rb["includeTrees"]:
    before=sum(len(ns) for _,_,ns in os.walk(full(ROOT,p)))
    copy_tree(ROOT,out,p); copied+=before

for p in rb.get("conditionalFiles",[]):
    if os.path.isfile(full(ROOT,p)):
        copy_file(ROOT,out,p); copied+=1
    elif man["releaseStatus"]=="release":
        sys.exit(f"Release runtime file is missing: {p}")
    else:
        print(f"WARN pre-release runtime file not built yet: {p}")

# W-322: controlled plugin release. Copy every locked plugin from the payload store into .obsidian/plugins.
rp=man["runtimePlugins"]
with open(full(ROOT,rp["lock"]),encoding="utf-8") as f:
    plock=yaml.safe_load(f)
if plock.get("schema")!=2:
    sys.exit("plugin-lock.yaml is not schema 2; run update-plugin-lock.py")
for pid in plock["plugins"]:
    src=full(ROOT,rp["payload"]+"/"+pid)
    if not os.path.isdir(src):
        sys.exit(f"Runtime plugin payload missing: {pid}")
    dst=full(out,".obsidian/plugins/"+pid)
    os.makedirs(dst,exist_ok=True)
    for n in sorted(os.listdir(src)):
        if n in ("main.js","manifest.json","styles.css","data.json"):
            shutil.copy2(os.path.join(src,n),os.path.join(dst,n)); copied+=1

gitignore='''# Generated by build-base.py (W-322). Governed plugin settings (data.json) ARE tracked;
# only per-machine and per-person state is ignored.
.obsidian/workspace.json
.obsidian/workspaces.json
.obsidian/author-code.txt
.obsidian/plugins/mdse-bootstrap/data.json
.obsidian/plugins/mdse-workbench/data.json
.obsidian/plugins/dataview/data.json
.obsidian/plugins/advanced-canvas/data.json
.obsidian/plugins/nodian/data.json
.obsidian/plugins/quickadd/data.json
.obsidian/plugins/table-exporter/data.json
Workbench Views/
.trash/
.DS_Store
Thumbs.db
'''
with open(full(out,".gitignore"),"w",encoding="utf-8",newline="\n") as f:
    f.write(gitignore)

vault=f'''# Generated by build-base.py from mdse-release.yaml. Do not remove mdse_release.
vault_uid: UNINITIALIZED
name: MDSE_Base_Vault
default_branch: main
mdse_release: "{man["mdseRelease"]}"
'''
with open(full(out,".vault.yaml"),"w",encoding="utf-8",newline="\n") as f:
    f.write(vault)

readme=f'''# MDSE Base Vault

Lean runtime base for MDSE release **{man["mdseRelease"]}**.

Runtime schemas:
- relationships {man["schemas"]["relationships"]}
- element-types {man["schemas"]["elementTypes"]}
- Local Model {man["schemas"]["localModel"]}

This vault intentionally does not contain the methodology workspace's Current State,
release manifest, Translator Definition, Decision Log, EA evidence, archives, or
Workbench design notes. Runtime rules are in
`99_System/10_Docs/MDSE Modeling Ruleset 1.23.md` and the schemas under
`99_System/03_Schemas`.

## Opening the vault

1. Clone the vault repository and open the folder as a vault in Obsidian {plock["obsidianMinVersion"]} or later.
2. When Obsidian asks, choose **Trust author and enable plugins** (turns off Restricted mode).
   Every plugin is already in the vault, pinned and configured; do not install or update plugins yourself.
3. MDSE Bootstrap asks once for your name and registers your author code, creating your note in
   `99_System/04_People`. Commit and sync with Git afterwards so others see it.
4. The status bar shows **MDSE: release OK** when the vault matches the controlled release.
   Click it to see the check; run **MDSE Bootstrap: Show release check** at any time.
5. Create notes with **Templater: Create new note from template** (templates in `99_System/05_Templates`).

## For the release owner

Before sharing, initialize `.vault.yaml` once with `Initialize-Vault.sh` or `Initialize-Vault.ps1`.
Initialization changes the vault UID/name and preserves `mdse_release`.
'''
with open(full(out,"README.md"),"w",encoding="utf-8",newline="\n") as f:
    f.write(readme)

for p in rb.get("forbiddenPaths",[]):
    if os.path.exists(full(out,p)):
        sys.exit(f"Forbidden workspace-only path leaked into runtime base: {p}")

lock_path=full(out,".obsidian/plugin-lock.yaml")
lock=open(lock_path,encoding="utf-8").read() if os.path.exists(lock_path) else ""
if man["tools"]["bootstrap"].get("sourceAvailable") is False and "mdse-bootstrap" in lock:
    sys.exit("Unavailable mdse-bootstrap is present in the generated runtime plugin lock")
wbid=man["tools"]["workbench"]["runtimePluginId"]
wbv=man["tools"]["workbench"].get("wb106Version")
if man["releaseStatus"]=="release" and man["tools"]["workbench"]["requiredForRelease"]:
    if wbid not in plock["plugins"] or not wbv or plock["plugins"][wbid]["version"]!=wbv:
        sys.exit("Release base does not pin the required WB-106-capable Workbench")

print(f"Built MDSE {man['mdseRelease']} lean runtime base at {out}")
print(f"Copied {copied} governed files (including {len(plock['plugins'])} runtime plugins) plus generated README.md, .gitignore and .vault.yaml")
print('Validate with: python3 "Base Vault/Testing/check-release.py" --base <output>')
