#!/usr/bin/env python3
"""Write or verify `.obsidian/plugin-lock.yaml` (schema 2) from the vendored runtime plugins (W-322).

Usage:
  python3 "Base Vault/Tools/v0.8.0/update-plugin-lock.py"          # rewrite lock + community-plugins.json
  python3 "Base Vault/Tools/v0.8.0/update-plugin-lock.py" --check  # exit 1 if either is stale

The plugin set, order, sources and settings policy are declared in PLUGINS below; versions and SHA-256
hashes are read from Base Vault/Runtime/Plugins/<id>/. Changing a plugin version is a release
decision: replace the vendored files, update PLUGINS if the source changes, run this script, log a W- entry.
"""
import argparse, hashlib, json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
PAYLOAD = os.path.join(ROOT, "Base Vault", "Runtime", "Plugins")
LOCK = os.path.join(ROOT, ".obsidian", "plugin-lock.yaml")
ENABLED = os.path.join(ROOT, ".obsidian", "community-plugins.json")
FILES = ("main.js", "manifest.json", "styles.css")

# id: (source, settings) — settings "governed" means a generated data.json ships with the release.
PLUGINS = {
    "mdse-bootstrap":     ("Test_Vault_ Bootstrap controlled build", "default"),
    "mdse-workbench":     ("spencerskelly/MDSE_Workbench 0.1.18 artifact b0c4e2c6bdfb96d36f51d8152b17be22592ef174 (verified build 37408465530; startup 37408519667)", "default"),
    "templater-obsidian": ("github.com/SilentVoid13/Templater release", "governed"),
    "fileclass":          ("github.com/mdelobelle/fileclass release", "governed"),
    "breadcrumbs":        ("github.com/michaelpporter/breadcrumbs release", "governed"),
    "obsidian-git":       ("github.com/Vinzent03/obsidian-git release", "governed"),
    "advanced-canvas":    ("github.com/Developer-Mike/obsidian-advanced-canvas release", "default"),
    "nodian":             ("github.com/akisantin/Nodian release", "default"),
    "quickadd":           ("github.com/chhoumann/quickadd release", "default"),
    "table-exporter":     ("github.com/wikty/obsidian-table-exporter release", "default"),
}
REQUIRED_CORE = ["bases", "canvas", "properties", "file-explorer", "command-palette"]
DISABLED_CORE = ["templates"]   # core Templates inserts Templater syntax unprocessed; Templater is the template path

def sha(p):
    with open(p, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

def vercmp(v):
    return tuple(int(x) if x.isdigit() else 0 for x in v.split("."))

lines = ["# GENERATED by Base Vault/Tools/v0.8.0-r2/update-plugin-lock.py (W-331). Controlled plugin release for MDSE vaults.",
         "# MDSE Bootstrap verifies the installed plugins against this file. Do not edit by hand.",
         "schema: 2"]
problems, minapp, body = [], "0", []
for pid, (source, settings) in PLUGINS.items():
    d = os.path.join(PAYLOAD, pid)
    mf = os.path.join(d, "manifest.json")
    if not os.path.isfile(mf) or not os.path.isfile(os.path.join(d, "main.js")):
        problems.append(f"{pid}: payload missing main.js or manifest.json"); continue
    m = json.load(open(mf, encoding="utf-8"))
    if m.get("id") != pid: problems.append(f"{pid}: manifest id is {m.get('id')}")
    if vercmp(m.get("minAppVersion", "0")) > vercmp(minapp): minapp = m.get("minAppVersion", "0")
    if settings == "governed" and not os.path.isfile(os.path.join(d, "data.json")):
        problems.append(f"{pid}: governed settings but no data.json (run build-plugin-config.py)")
    body += [f"  {pid}:", f"    version: \"{m['version']}\"", f"    source: \"{source}\"", f"    settings: {settings}", "    sha256:"]
    locked_files = list(FILES) + (["data.json"] if settings == "governed" else [])
    for fn in locked_files:
        p = os.path.join(d, fn)
        if os.path.isfile(p): body.append(f"      {fn}: {sha(p)}")
lines += [f"obsidianMinVersion: \"{minapp}\"",
          "requiredCorePlugins: [" + ", ".join(REQUIRED_CORE) + "]",
          "disabledCorePlugins: [" + ", ".join(DISABLED_CORE) + "]",
          "plugins:"] + body
lock_text = "\n".join(lines) + "\n"
enabled_text = json.dumps(list(PLUGINS), indent=2) + "\n"

ap = argparse.ArgumentParser(); ap.add_argument("--check", action="store_true"); a = ap.parse_args()
for p in problems: print("PROBLEM", p)
stale = []
for path, text in ((LOCK, lock_text), (ENABLED, enabled_text)):
    cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if cur != text:
        stale.append(os.path.relpath(path, ROOT))
        if not a.check:
            with open(path, "w", encoding="utf-8", newline="\n") as f: f.write(text)
if a.check:
    for s in stale: print("STALE", s)
    sys.exit(1 if stale or problems else 0)
print(f"lock written for {len(PLUGINS)} plugins; Obsidian {minapp}+; {len(stale)} file(s) updated")
sys.exit(1 if problems else 0)
