#!/usr/bin/env python3
"""IMP-009 whole-model output acceptance check for importer v0.8.14.

Usage:
  python3 imp009_output_acceptance.py /path/to/generated/vault

Exit 0 means the headless IMP-009 checks passed. It does NOT replace the
required Workbench read/edit/reload acceptance on the same vault.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path

IMPORT_DIR = Path("99_System/11_Import")
STATE = IMPORT_DIR / "Import State.json"
MANIFEST = IMPORT_DIR / "Run Manifest.md"
SOURCE_MAP = IMPORT_DIR / "Local Model Source Map.csv"
LEDGER = IMPORT_DIR / "Ledger.csv"
DEF_REVIEW = IMPORT_DIR / "Review - Definitionless Local Endpoints.csv"
SEM_REVIEW = IMPORT_DIR / "Review - Semantic and Connectors.csv"
OLD_ADDED_PORTS = IMPORT_DIR / "Review - Added Ports.csv"

LOCAL_START = "<!-- MDSE:LOCAL-MODEL START schema=0.3 -->"
LOCAL_END = "<!-- MDSE:LOCAL-MODEL END -->"
EP_BLOCK = re.compile(r"^\^(ep-\d{17}[a-z-]{13})\s*$")
EP_REF = re.compile(r"#\^(ep-\d{17}[a-z-]{13})\b")
GUID_CLEAN = re.compile(r"[^0-9a-f]")

fails: list[str] = []
warns: list[str] = []
passes: list[str] = []


def fail(msg: str) -> None:
    fails.append(msg)


def warn(msg: str) -> None:
    warns.append(msg)


def ok(msg: str) -> None:
    passes.append(msg)


def read_text(root: Path, rel: Path) -> str:
    p = root / rel
    if not p.is_file():
        fail(f"missing required file: {rel.as_posix()}")
        return ""
    try:
        return p.read_text(encoding="utf-8")
    except Exception as ex:
        fail(f"cannot read {rel.as_posix()}: {ex}")
        return ""


def read_csv(root: Path, rel: Path) -> list[dict[str, str]]:
    text = read_text(root, rel)
    if not text:
        return []
    try:
        return list(csv.DictReader(text.splitlines()))
    except Exception as ex:
        fail(f"cannot parse CSV {rel.as_posix()}: {ex}")
        return []


def norm_guid(v: str) -> str:
    return GUID_CLEAN.sub("", (v or "").lower())


def manifest_value(text: str, label: str) -> str:
    m = re.search(rf"^- {re.escape(label)}:\s*(.+?)\s*$", text, re.M)
    return m.group(1).strip() if m else ""


def require_columns(rows: list[dict[str, str]], required: set[str], label: str) -> None:
    if not rows:
        return
    got = set(rows[0].keys())
    missing = sorted(required - got)
    if missing:
        fail(f"{label} missing columns: {', '.join(missing)}")
    else:
        ok(f"{label} contains required columns")


def find_record(lines: list[str], block_index: int) -> tuple[str, list[str]]:
    section = ""
    start = 0
    for i in range(block_index, -1, -1):
        line = lines[i]
        if line.startswith("### ") and not line.startswith("#### "):
            section = line[4:].strip()
            break
    for i in range(block_index, -1, -1):
        if lines[i].startswith("#### "):
            start = i
            break
    return section, lines[start:block_index + 1]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("vault", help="fresh whole-model vault generated by importer v0.8.14")
    args = ap.parse_args()
    root = Path(args.vault).expanduser().resolve()

    if not root.is_dir():
        print(f"FAIL vault does not exist: {root}")
        return 2

    # Transaction/run identity.
    state_text = read_text(root, STATE)
    state = {}
    if state_text:
        try:
            state = json.loads(state_text)
        except Exception as ex:
            fail(f"Import State.json is invalid JSON: {ex}")

    if state:
        if state.get("status") == "IMPORT_COMPLETE":
            ok("transaction state is IMPORT_COMPLETE")
        else:
            fail(f"transaction state is {state.get('status')!r}, expected IMPORT_COMPLETE")
        version = ((state.get("importer") or {}).get("version") or "")
        if version == "0.8.14":
            ok("Import State records importer v0.8.14")
        else:
            fail(f"Import State importer version is {version!r}, expected 0.8.14")
        if state.get("scope") == "WHOLE MODEL":
            ok("run scope is WHOLE MODEL")
        else:
            fail(f"IMP-009 acceptance requires WHOLE MODEL scope; got {state.get('scope')!r}")
        sha = ((state.get("source") or {}).get("sha256") or "")
        if re.fullmatch(r"[0-9a-f]{64}", sha):
            ok("source SHA-256 is present")
        else:
            fail("source SHA-256 missing or invalid")
        run_status = state.get("runStatus") or {}
        if run_status.get("write") == "WRITE_PASS":
            ok("transaction runStatus.write is WRITE_PASS")
        else:
            fail(f"transaction write status is {run_status.get('write')!r}")

    manifest = read_text(root, MANIFEST)
    if "0.8.14" in manifest:
        ok("Run Manifest identifies importer v0.8.14")
    else:
        fail("Run Manifest does not identify importer v0.8.14")
    if manifest_value(manifest, "Local Model schema") == "0.3":
        ok("Run Manifest records Local Model schema 0.3")
    else:
        fail("Run Manifest Local Model schema is not 0.3")

    mcount = manifest_value(manifest, "Definitionless contextual endpoints (W-377)")
    try:
        manifest_def_count = int(mcount)
    except Exception:
        manifest_def_count = -1
        fail(f"Run Manifest definitionless endpoint count is invalid: {mcount!r}")

    # Core evidence.
    review = read_csv(root, DEF_REVIEW)
    require_columns(
        review,
        {"ea_guid", "source_object_id", "ea_type", "ea_name", "category", "owner_note",
         "local_id", "assembly", "block_note", "block_ports", "reason"},
        DEF_REVIEW.name,
    )
    if review:
        ok(f"definitionless endpoint review contains {len(review)} rows")
    else:
        fail("definitionless endpoint review has no data rows; real EA8647 acceptance did not exercise W-377")

    if manifest_def_count >= 0 and manifest_def_count == len(review):
        ok("Run Manifest definitionless count matches review CSV")
    elif manifest_def_count >= 0:
        fail(f"Run Manifest definitionless count {manifest_def_count} != review rows {len(review)}")

    if (root / OLD_ADDED_PORTS).exists():
        fail("legacy Review - Added Ports.csv exists")
    else:
        ok("legacy Added Ports review is absent")

    source_map = read_csv(root, SOURCE_MAP)
    require_columns(
        source_map,
        {"source_model_id", "source_key", "owner_uid", "local_id", "local_kind",
         "ea_guid", "ea_source_kind", "ea_owner_guid"},
        SOURCE_MAP.name,
    )
    ledger = read_csv(root, LEDGER)
    require_columns(
        ledger,
        {"ea_guid", "source_kind", "ea_type", "ea_name", "outcome", "rule", "uid", "id", "folded_into_uid"},
        LEDGER.name,
    )
    semantic = read_csv(root, SEM_REVIEW)
    require_columns(
        semantic,
        {"source_guid", "category", "relationship", "from_type", "from_name",
         "to_type", "to_name", "detail"},
        SEM_REVIEW.name,
    )

    # Reject old synthetic Port evidence.
    for rel in (SOURCE_MAP, LEDGER, DEF_REVIEW, SEM_REVIEW):
        txt = read_text(root, rel)
        if "portgroup:" in txt:
            fail(f"legacy synthetic portgroup evidence found in {rel.name}")
    if not any("portgroup:" in read_text(root, rel) for rel in (SOURCE_MAP, LEDGER, DEF_REVIEW, SEM_REVIEW)):
        ok("no portgroup: evidence remains in core import evidence")

    local_ledger = [
        r for r in ledger
        if (r.get("source_kind") or "") == "element"
        and (r.get("ea_type") or "") == "Port"
        and (r.get("outcome") or "") == "local endpoint"
    ]
    if len(local_ledger) == len(review):
        ok("Ledger local-endpoint Port count matches definitionless review count")
    else:
        fail(f"Ledger has {len(local_ledger)} local-endpoint Ports; review has {len(review)}")
    bad_identity = [r for r in local_ledger if (r.get("uid") or "").strip() or (r.get("id") or "").strip()]
    if bad_identity:
        fail(f"{len(bad_identity)} contextual-only Ports unexpectedly received first-class uid/id")
    elif local_ledger:
        ok("contextual-only Port ledger rows have no first-class note uid/id")

    review_ids: dict[str, dict[str, str]] = {}
    object_ids: set[str] = set()
    for row in review:
        local_id = (row.get("local_id") or "").strip()
        obj_id = (row.get("source_object_id") or "").strip()
        if not obj_id:
            fail(f"definitionless endpoint row missing source_object_id for {row.get('ea_guid')}")
        else:
            object_ids.add(obj_id)
        if not local_id:
            fail(f"definitionless endpoint source Object_ID {obj_id or '?'} was not materialized as a local endpoint")
            continue
        if local_id in review_ids:
            fail(f"duplicate definitionless review local_id: {local_id}")
        review_ids[local_id] = row

    sm_by_local: dict[str, list[dict[str, str]]] = {}
    for row in source_map:
        sm_by_local.setdefault((row.get("local_id") or "").strip(), []).append(row)
    for local_id, row in review_ids.items():
        matches = [x for x in sm_by_local.get(local_id, []) if (x.get("local_kind") or "") == "endpoint"]
        if len(matches) != 1:
            fail(f"{local_id} has {len(matches)} endpoint Source Map rows, expected 1")
            continue
        if norm_guid(matches[0].get("ea_guid") or "") != norm_guid(row.get("ea_guid") or ""):
            fail(f"{local_id} Source Map EA GUID does not match definitionless review")
    if review_ids and not any("Source Map" in f for f in fails):
        ok("definitionless endpoint rows resolve one-to-one through Local Model Source Map")

    # Scan model Markdown and validate precise local records/references.
    target_ids = set(review_ids)
    target_hits: dict[str, list[tuple[Path, str, list[str]]]] = {x: [] for x in target_ids}
    all_endpoint_blocks: set[str] = set()
    all_endpoint_refs: list[tuple[Path, str]] = []
    connection_refs: set[str] = set()

    for p in root.rglob("*.md"):
        if ".git" in p.parts or ".obsidian" in p.parts:
            continue
        try:
            lines = p.read_text(encoding="utf-8").splitlines()
        except Exception as ex:
            fail(f"cannot scan Markdown {p.relative_to(root)}: {ex}")
            continue
        in_local = False
        section = ""
        for idx, line in enumerate(lines):
            if line.strip() == LOCAL_START:
                in_local = True
                section = ""
                continue
            if line.strip() == LOCAL_END:
                in_local = False
                section = ""
                continue
            if in_local and line.startswith("### ") and not line.startswith("#### "):
                section = line[4:].strip()
            m = EP_BLOCK.match(line.strip())
            if m:
                local_id = m.group(1)
                all_endpoint_blocks.add(local_id)
                if local_id in target_ids:
                    sec, rec = find_record(lines, idx)
                    target_hits[local_id].append((p, sec, rec))
            if in_local:
                for ref in EP_REF.findall(line):
                    all_endpoint_refs.append((p, ref))
                    if section == "Connections" and line.startswith(("- endpointA:", "- endpointB:")):
                        connection_refs.add(ref)

    broken = [(p, ref) for p, ref in all_endpoint_refs if ref not in all_endpoint_blocks]
    if broken:
        sample = ", ".join(f"{p.relative_to(root)} -> {ref}" for p, ref in broken[:8])
        fail(f"{len(broken)} Local Model endpoint block references are unresolved; examples: {sample}")
    else:
        ok(f"all {len(all_endpoint_refs)} Local Model endpoint block references resolve")

    for local_id in sorted(target_ids):
        hits = target_hits.get(local_id, [])
        if len(hits) != 1:
            fail(f"{local_id} appears as a Markdown endpoint block {len(hits)} times, expected 1")
            continue
        path, section, record = hits[0]
        if section != "Local Interfaces":
            fail(f"{local_id} is under section {section!r} in {path.relative_to(root)}, expected Local Interfaces")
        rec_text = "\n".join(record)
        if "- definition:" in rec_text:
            fail(f"{local_id} unexpectedly has a reusable definition in {path.relative_to(root)}")
        if "- usage:" in rec_text:
            fail(f"{local_id} unexpectedly has usage without a definition in {path.relative_to(root)}")
    if target_ids and not any("unexpectedly has" in f or "appears as a Markdown endpoint block" in f or "expected Local Interfaces" in f for f in fails):
        ok("definitionless endpoints exist as schema-0.3 Local Interfaces without definition/usage")

    referenced_definitionless = target_ids & {ref for _, ref in all_endpoint_refs}
    if referenced_definitionless:
        ok(f"{len(referenced_definitionless)} definitionless endpoints are addressable through persisted local block links")
    else:
        warn("no definitionless endpoint is referenced by another persisted local block link; this source run does not exercise topology use")

    connection_definitionless = target_ids & connection_refs
    if connection_definitionless:
        ok(f"{len(connection_definitionless)} definitionless endpoints participate in Local Model connection endpoint links")
    else:
        warn("no definitionless endpoint participates in a persisted Local Model connection; topology acceptance needs a targeted case")

    # W-380: connector evidence must resolve to the exact contextual EA Port rows.
    w377_rows = [r for r in semantic if "W-377 definitionless contextual endpoint" in (r.get("detail") or "")]
    if not w377_rows:
        warn("semantic review contains no W-377 connector rows; connector-evidence acceptance was not exercised")
    else:
        unresolved = []
        for row in w377_rows:
            keys = {(row.get("from_name") or "").strip(), (row.get("to_name") or "").strip()}
            touched = {k.split(":", 1)[1] for k in keys if k.startswith("localendpoint:")}
            if not (touched & object_ids):
                unresolved.append(row.get("source_guid") or "<no-guid>")
        if unresolved:
            fail(f"{len(unresolved)} W-377 connector review rows do not resolve to a definitionless source Object_ID")
        else:
            ok(f"all {len(w377_rows)} W-377 connector review rows resolve to definitionless source Object_IDs")

    print("IMP-009 headless acceptance")
    print(f"vault: {root}")
    for msg in passes:
        print("PASS", msg)
    for msg in warns:
        print("WARN", msg)
    for msg in fails:
        print("FAIL", msg)

    if fails:
        print(f"RESULT: FAIL ({len(fails)} failures, {len(warns)} warnings)")
        return 2

    print(f"RESULT: HEADLESS PASS ({len(passes)} checks, {len(warns)} warnings)")
    print("PENDING: open this same vault with the pinned Workbench 0.1.17 candidate and prove schema-0.3 read/navigation/edit/reload on at least one definitionless endpoint.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
